# TLS Dynamic Configuration file

tls:
  certificates:
    - certFile: /ssl-certs/cloudflare/fullchain.pem
      keyFile: /ssl-certs/cloudflare/privkey.pem
    - certFile: /ssl-certs/home/fullchain.pem
      keyFile: /ssl-certs/home/privkey.pem

http:
  serversTransports:
    httpsNoVerify:
      insecureSkipVerify: true