version: "3.9"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TOKEN:?UNSET_TOKEN_ERROR}
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true
    name: proxy