version: "3.9"

services:
  lldap:
    image: lldap/lldap:stable-alpine-rootless
    depends_on:
      - db
    restart: unless-stopped
    # ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      #- "17170:17170"
    expose:
      - "17170" # Expose the web front-end
      - "3890" # Expose the LDAP port
    networks:
      - default
      - proxy # Proxy network (for Traefik) (LDAP will be routed through Traefik as well)
      - ldap # Use the LDAP network
    volumes:
      - "data:/data"
    user: ${UID:-1000}:${GID:-1000} # Run as the lldap user, default UID and GID are 1000
    environment:
      TZ: ${TZ:-Europe/Rome}
      LLDAP_JWT_SECRET: ${LDAP_JWT_SECRET:?UNSET_LDAP_JWT_SECRET_ERROR}
      LLDAP_KEY_SEED: ${LDAP_KEY_SEED:?UNSET_LDAP_KEY_SEED_ERROR}
      LLDAP_LDAP_BASE_DN: "${LDAP_BASE_DN:-dc=example,dc=com}" # The base DN for LDAP
      LLDAP_LDAP_USER_PASS: ${LDAP_ADMIN_PW:?UNSET_LDAP_ADMIN_PW_ERROR}
      # If using LDAPS, set enabled true and configure cert and key path
      # - LLDAP_LDAPS_OPTIONS__ENABLED=true
      # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # Set a different database:
      LLDAP_DATABASE_URL: postgres://lldap:lldap@db/lldap
      # If using SMTP, set the following variables
      # - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      # - LLDAP_SMTP_OPTIONS__SERVER=smtp.example.com
      # - LLDAP_SMTP_OPTIONS__PORT=465 # Check your smtp providor's documentation for this setting
      # - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
      # - LLDAP_SMTP_OPTIONS__USER=no-reply@example.com # The SMTP user, usually your email address
      # - LLDAP_SMTP_OPTIONS__PASSWORD=PasswordGoesHere # The SMTP password
      # - LLDAP_SMTP_OPTIONS__FROM=no-reply <no-reply@example.com> # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
      # - LLDAP_SMTP_OPTIONS__TO=admin <admin@example.com> # Same for reply-to, optional.
    labels:
      traefik.enable: true
      traefik.http.routers.lldap-web.entrypoints: websecure
      traefik.http.routers.lldap-web.rule: Host(`${PRIVATE_HOST:?UNSET_PRIVATE_HOST_ERROR}`) # Use this host
      traefik.http.routers.lldap-web.tls: true # Enable TLS for this router
      traefik.http.routers.lldap-web.tls.certresolver: cfresolver # Use Cloudflare
      traefik.http.services.lldap.loadbalancer.server.port: 17170 # The web port the service is listening on
  
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lldap
      POSTGRES_USER: lldap
      POSTGRES_PASSWORD: lldap
    networks:
      - default

networks:
  proxy:
    external: true
    name: proxy
  ldap:
    external: true
    name: ldap

volumes:
  data:
  pgdata: