version: '3.9'

services:
  proxy:
    image: purplei2p/i2pd:latest-release
    networks:
      - default
      - proxy
    ports:
      - 4444:4444 # HTTP Proxy
      - 4445:4445 # SOCKS Proxy
      - 7656:7656 # SAM
    #  - 7070:7070 # Web console
    volumes:
      - data:/home/i2pd/data
    labels:
      traefik.enable: true
      traefik.http.routers.i2p.entrypoints: websecure
      traefik.http.routers.i2p.rule: Host(`${PRIVATE_HOST:?UNSET_PRIVATE_HOST_ERROR}`)
      traefik.http.routers.i2p.tls: true
      traefik.http.services.proxy-i2p.loadbalancer.server.port: 7070

networks:
  proxy:
    external: true
    name: proxy

volumes:
  data: