version: '3.9'
services:
  openldap-bitnami:
    image: bitnami/openldap:2.6
    #hostname: ${HOSTNAME:?UNSET_HOSTNAME_ERROR}
    hostname: master01.ldap.robigan.com
    environment:
      LDAP_ROOT: "${LDAP_ROOT:?UNSET_LDAP_ROOT_ERROR}"
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PW:?UNSET_LDAP_ADMIN_PW_ERROR}
      LDAP_CONFIG_ADMIN_ENABLED: yes
      LDAP_ALLOW_ANON_BINDING: no
      LDAP_EXTRA_SCHEMAS: "cosine,inetorgperson,nis,memberof"
    ports:
      - 1389:1389
    networks:
      - default
      - ldap
    volumes:
      - openldap_data:/bitnami/openldap
    restart: unless-stopped

networks:
  ldap:
    external: true
    name: ldap

volumes:
  openldap_data:
