version: '3.9'

services:
  server:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - hs-configs:/config
    networks:
      - default
      - proxy
    expose:
      - 8123
    ports:
      - 1400:1400/tcp # Spotify
      # - 8123:8123/tcp # Web UI
      - 21063:21063/tcp # Homekit
    labels:
      traefik.enable: true
      traefik.http.routers.hass.entrypoints: websecure
      traefik.http.routers.hass.rule: Host(`${PRIVATE_HOST:?UNSET_PRIVATE_HOST_ERROR}`)
      traefik.http.routers.hass.tls: true
      traefik.http.routers.hass.tls.certresolver: cfresolver
      traefik.http.routers.hass-public.entrypoints: websecure
      traefik.http.routers.hass-public.rule: Host(`${PUBLIC_HOST:?UNSET_PUBLIC_HOST_ERROR}`)
      traefik.http.routers.hass-public.tls: true
      traefik.http.routers.hass-public.tls.certresolver: cfresolver
      traefik.http.routers.hass-public.middlewares: cloudflare, crowdsec
      traefik.http.services.server-hass.loadbalancer.server.port: 8123 # Specify port 8123
  
  repeater:
    image: monstrenyatko/mdns-repeater:latest
    network_mode: host
    restart: unless-stopped
    command: mdns-repeater-app -f ${HOST_INTERFACES} br-hass
      
volumes:
  hs-configs:
    name: hass-configs

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-hass
  proxy:
    name: proxy
    external: true