version: '3.9'

services:
  server:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - hs-configs:/config
    networks:
      - default
      - proxy
    expose:
      - 8123
    labels:
      traefik.enable: true
      traefik.http.routers.hass.entrypoints: websecure
      traefik.http.routers.hass.rule: Host(`${PRIVATE_HOST:?UNSET_PRIVATE_HOST_ERROR}`)
      traefik.http.routers.hass.tls: true
      traefik.http.routers.hass-public.entrypoints: websecure
      traefik.http.routers.hass-public.rule: Host(`${PUBLIC_HOST:?UNSET_PUBLIC_HOST_ERROR}`)
      traefik.http.routers.hass-public.tls: true
      traefik.http.routers.hass-public.middlewares: cloudflare, crowdsec
      
volumes:
  hs-configs:
    name: hass-configs

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-hass
  proxy:
    name: proxy
    external: true