version: '3.9'

services:
  proxy:
    image: divax/i2p:current
    networks:
      - default
      - proxy
    volumes:
      - data:/home/i2pd/data
    # expose:
    #   - 4444
    #   - 4445
    #   - 7656
    #   - 7070
    ports:
      - 4444:4444 # HTTP Proxy
      - 4445:4445 # SOCKS Proxy
      - 7656:7656 # SAM
      - 7070:7070 # Web console
    environment:
      ENABLE_HTTPPROXY: ${ENABLE_HTTP:-1}  # Usage of I2P proxy through HTTP protocol
      ENABLE_SOCKSPROXY: ${ENABLE_SOCKS:-1} # Usage of I2P proxy through SOCKS protocol
      ENABLE_SAM: ${ENABLE_SAM:-0} # Enable I2P SAM
      BANDWIDTH: ${BANDWIDTH:-P} # Sets the bandwidth limit to 2048KB/s. Recommend lower values.
      ENABLE_UPNP: ${ENABLE_UPNP:-1} # Enable UPNP so that ports are opened on the router
      LOGLEVEL: ${LOG_LEVEL:-info} # Set log level, see https://hub.docker.com/r/divax/i2p
    labels:
      traefik.enable: true
      traefik.http.routers.i2p.entrypoints: websecure
      traefik.http.routers.i2p.rule: Host(`${PRIVATE_HOST:?UNSET_PRIVATE_HOST_ERROR}`)
      traefik.http.routers.i2p.tls: true
      traefik.http.services.proxy-i2p.loadbalancer.server.port: 7070

networks:
  proxy:
    external: true
    name: proxy

volumes:
  data: