version: "3.9"

services:
  reverse-proxy:
    image: traefik:v2.9
    networks:
      - default # Defualt network that Traefik can use for update checking
      - proxy # Proxy network
    ports:
      - 443:443 # Websecure port
      - 80:80 # Web port
    restart: unless-stopped
    command:
      - "--global.sendanonymoususage=false" # Disable anonymous usage data
      - "--entrypoints.web.address=:80" # Provide an entrypoint for HTTP traffic
      # Doesn't redirect by default to HTTPS scheme for services that legitimately need HTTP
      - "--entrypoints.websecure.address=:443" # Provide a secure entrypoint for HTTPS traffic
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure" # Always redirect the web entrypoint to websecure entrypoint
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https" # Upgrade the scheme to https
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true" # Use a permanent redirect
      - "--api.insecure=false" # Disable insecure API
      - "--api.dashboard=true" # But do enable the dashboard
      - "--providers.docker=true" # Enable docker provider
      - "--providers.docker.exposedbydefault=false" # Disable exposing services by default
      - "--providers.docker.network=proxy" # Set the default docker network to proxy
      - "--accesslog=${ACCESS_LOG:-false}" # Access log definition, values are 'true' or 'false' 
      - "--log.level=${LOG_LEVEL:-ERROR}" # Log level definition, see https://doc.traefik.io/traefik/observability/logs/#level
      - "--experimental.plugins.cloudflarewarp.modulename=github.com/BetterCorp/cloudflarewarp" # Add cloudflarewarp plugin
      - "--experimental.plugins.cloudflarewarp.version=v1.3.3" # Specify version(s)
      # Configure Cloudflare DNS Challenge
      - "--certificatesresolvers.cfresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.cfresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cfresolver.acme.email=robigan@robigan.com"
      - "--certificatesresolvers.cfresolver.acme.storage=/acme/acme.json"
    labels:
      # Enable traefik labels for this definition
      traefik.enable: true
      # Setup router, see https://community.traefik.io/t/serving-traefiks-internal-dashboard-behind-traefik-itself/3457/7
      traefik.http.routers.traefik.entrypoints: websecure # Setup an http router to the dashboard
      traefik.http.routers.traefik.rule: Host(`${PRIVATE_HOST:?UNSET_PRIVATE_HOST_ERROR}`) # Use this host
      traefik.http.routers.traefik.tls: true # Enable TLS for this router
      traefik.http.routers.traefik.tls.certresolver: cfresolver # Use the Let's Encrypt Cert
      traefik.http.routers.traefik.service: api@internal # Route to api service
      # Define cloudflare middleware
      traefik.http.middlewares.cloudflare.plugin.cloudflarewarp.disableDefault: false # Set the disable default to false. Creates the cloudflarewarp middleware and uses IPs listed at cloudflare.com
      # Define crowdsec bouncer middleware
      traefik.http.middlewares.crowdsec.forwardauth.address: http://bouncer:8080/api/v1/forwardAuth
      traefik.http.middlewares.crowdsec.forwardauth.trustForwardHeader: true # Should be disabled but it isn't picking up trusted headers from cloudflare, therefore it sends the internal IP for querying instead
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mount the docker socket so that traefik can monitor it
      - acme:/acme # Directory for auto generated certificates
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_TOKEN:?UNSET_CF_DNS_TOKEN_ERROR}

  bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:latest
    restart: unless-stopped
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_KEY:-0}
      CROWDSEC_AGENT_HOST: ${CROWDSEC_HOST:-host.docker.internal:7070}
      CROWDSEC_BOUNCER_LOG_LEVEL: ${LOG_LEVEL_BOUNCER:-1} # Uses zerolog levels
      GIN_MODE: release
      TRUSTED_PROXIES: 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32 # List of cloudflare IPs to trust forwarding for
    networks:
      - default # Defualt network that we can use to communicate with Traefik
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 8080

networks:
  proxy: # Connect to proxy network
    # NOTE: Proxy network is external. When setting it up, it should always be internal, so not routable to the internet
    external: true
    name: proxy

volumes:
  acme: # Volume to store automatically generated certificates
